#!/usr/bin/env bash
#
# bootstrap installs things.

# Get admin access to install the programs
[ "$UID" -eq 0 ] || exec sudo bash "$0" "$@"

cd "$(dirname "$0")"
DOTFILES_ROOT=$(pwd -P)

set -e

echo ''

## COLOUR PRINTING FUNCTIONS ##
info () {
  printf "\r  [ \033[00;34m..\033[0m ] $1\n"
}

user () {
  printf "\r  [ \033[0;33m??\033[0m ] $1\n"
}

success () {
  printf "\r\033[2K  [ \033[00;32mOK\033[0m ] $1\n"
}

fail () {
  printf "\r\033[2K  [\033[0;31mFAIL\033[0m] $1\n"
  echo ''
  exit
}

## Create the git/gitconfig.local.symlink file to setup your git profile
setup_gitconfig () {
  if ! [ -f git/gitconfig.local.symlink ]
  then
    info 'setup gitconfig'

    git_credential='cache'
    if [ "$(uname -s)" == "Darwin" ]
    then
      git_credential='osxkeychain'
    fi

    user ' - What is your github author name?'
    read -e git_authorname
    user ' - What is your github author email?'
    read -e git_authoremail

    sed -e "s/AUTHORNAME/$git_authorname/g" -e "s/AUTHOREMAIL/$git_authoremail/g" -e "s/GIT_CREDENTIAL_HELPER/$git_credential/g" git/gitconfig.local.symlink.example > git/gitconfig.local.symlink

    success 'gitconfig'
  fi
}

install_programs() {
  # find the installers and run them iteratively
  info "Run installers"
  find -H "$DOTFILES_ROOT" -name install.sh | while read installer ; do sh -c "${installer}" ; done

  for installer in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name 'install.sh')
  do
    ($installer && success "$(dirname "$installer") Installed ") || fail "$(dirname "$installer") NOT Installed ")
  done
}

## Symlink config files with user prompts to confirm what action to take
link_file () {
  local src=$1 dst=$2

  local overwrite= backup= skip=
  local action=

  if [ -f "$dst" -o -d "$dst" -o -L "$dst" ]
  then

    if [ "$overwrite_all" == "false" ] && [ "$backup_all" == "false" ] && [ "$skip_all" == "false" ]
    then

      local currentSrc="$(readlink $dst)"

      if [ "$currentSrc" == "$src" ]
      then

        skip=true;

      else

        user "File already exists: $dst ($(basename "$src")), what do you want to do?\n\
        [s]kip, [S]kip all, [o]verwrite, [O]verwrite all, [b]ackup, [B]ackup all?"
        read -n 1 action

        case "$action" in
          o )
            overwrite=true;;
          O )
            overwrite_all=true;;
          b )
            backup=true;;
          B )
            backup_all=true;;
          s )
            skip=true;;
          S )
            skip_all=true;;
          * )
            ;;
        esac

      fi

    fi

    overwrite=${overwrite:-$overwrite_all}
    backup=${backup:-$backup_all}
    skip=${skip:-$skip_all}

    if [ "$overwrite" == "true" ]
    then
      rm -rf "$dst"
      success "removed $dst"
    fi

    if [ "$backup" == "true" ]
    then
      mv "$dst" "${dst}.backup"
      success "moved $dst to ${dst}.backup"
    fi

    if [ "$skip" == "true" ]
    then
      success "skipped $src"
    fi
  fi

  if [ "$skip" != "true" ]  # "false" or empty
  then
    ln -s "$1" "$2"
    success "linked $1 to $2"
  fi
}

## For every directory in the dotfile directory, link all .symlink config files to a folder
## in $HOME that has the same name with a leading period
## eg. dotfiles/vscode/settings.json.symlink ---> ~/.vscode/settings.json 
install_dotfiles () {
  info 'Applying my dotfiles'

  local overwrite_all=false backup_all=false skip_all=false

  for src in $(find -H "$DOTFILES_ROOT" -maxdepth 2 -name '*.symlink' -not -path '*.git*')
  do
    configdir="$(dirname "$src")"
    if [ -f ""$configdir"/symlink.dir" ]
    then
      read -r custom_dst < ""$configdir"/symlink.dir"
      eval custom_dst="$custom_dst" #expand variables such as $HOME

      if [ -d "$custom_dst" ]
      then
        dst=$custom_dst
      else
        fail "Directory listed in "$configdir"/symlink.dir ("$custom_dst") doesn't exist" && exit 1 # The directory in symlink.dir should exist, check install process if break
      fi
    else
      dst="$HOME/.$(basename "${src%.*}")"
    fi
    link_file "$src" "$dst"
  done
}

setup_gitconfig
install_programs
install_dotfiles

echo ''
echo '  All installed!'
