#!/usr/bin/bash

# find the installers and run them iteratively
find -H . -name install.sh | while read installer ; do sh -c "${installer}" && \
                                                       echo "$(dirname "$installer") Installed" || \
                                                       echo "$(dirname "$installer") NOT Installed" ; \
                                                       done
